// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainees_Track_Courses_MVC.Models;

#nullable disable

namespace Trainees_Track_Courses_MVC.Migrations
{
    [DbContext(typeof(TraineesDBContext))]
    [Migration("20230814050730_inti")]
    partial class inti
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trainees_Track_Courses_MVC.Models.Courses", b =>
                {
                    b.Property<int>("CrsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrsID"));

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CrsID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Trainees_Track_Courses_MVC.Models.Tracks", b =>
                {
                    b.Property<int>("TrcID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrcID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TrcID");

                    b.ToTable("Track");
                });

            modelBuilder.Entity("Trainees_Track_Courses_MVC.Models.Trainees", b =>
                {
                    b.Property<int>("TrnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrnID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrackID")
                        .HasColumnType("int");

                    b.Property<string>("TrnName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.HasKey("TrnID");

                    b.HasIndex("CourseID");

                    b.HasIndex("TrackID");

                    b.ToTable("Trainee");
                });

            modelBuilder.Entity("Trainees_Track_Courses_MVC.Models.Trainees", b =>
                {
                    b.HasOne("Trainees_Track_Courses_MVC.Models.Courses", "courses")
                        .WithMany("trainees")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainees_Track_Courses_MVC.Models.Tracks", "tracks")
                        .WithMany("trainees1")
                        .HasForeignKey("TrackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("courses");

                    b.Navigation("tracks");
                });

            modelBuilder.Entity("Trainees_Track_Courses_MVC.Models.Courses", b =>
                {
                    b.Navigation("trainees");
                });

            modelBuilder.Entity("Trainees_Track_Courses_MVC.Models.Tracks", b =>
                {
                    b.Navigation("trainees1");
                });
#pragma warning restore 612, 618
        }
    }
}
